import "./globals.css";

export const metadata = {
  title: {
    template: 'my-app | %s',
    default: 'my-app'
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="mx-10">{children}</body>
    </html>
  );
}
