import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { Roboto } from "next/font/google";
import IconButton from "@mui/material/IconButton";
import MenuIcon from "@mui/icons-material/Menu";
import Nav from "./components/nav";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: {
    template: "my-app | %s",
    default: "my-app",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <AppRouterCacheProvider>
          <header className="flex w-full h-[64px] bg-green-200">
            <div className="w-[64px] md:hidden content-center m-auto">
              <IconButton size="large">
                <MenuIcon />
              </IconButton>
            </div>
            <div className="w-full">header</div>
          </header>
          <div className="flex h-[500px]">
            <div className="max-md:hidden min-w-[300px] w-[300px] p-4 bg-red-200">
              <Nav />
            </div>
            <div className="w-full p-4">{children}</div>
          </div>
          <footer className="p-8 w-full h-[80px] bg-amber-200">footer</footer>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
